package model;
// Generated Aug 23, 2017 11:25:57 AM by Hibernate Tools 4.3.1

/**
 * Se generated by hbm2java
 */
public class Se implements java.io.Serializable {

    private String name;
    private char gender;
    private int password;
    private double balance;

    public Se() {
    }

    public Se(String name, char gender, int password, double balance) {
        this.name = name;
        this.gender = gender;
        this.password = password;
        this.balance = balance;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public char getGender() {
        return this.gender;
    }

    public void setGender(char gender) {
        this.gender = gender;
    }

    public int getPassword() {
        return this.password;
    }

    public void setPassword(int password) {
        this.password = password;
    }

    public double getBalance() {
        return this.balance;
    }

    public void setBalance(double balance) {
        this.balance = balance;
    }

    public void deposit(double x) {
        balance = balance + x;
    }

    public void withdraw(double x) {
        balance = balance - x;
    }

}
